### ISSUE TITLE
apidevtools.github.io cname broke?

### ISSUE THREAD

**Issue by ghost** [APIDevTools/apidevtools.github.io#1]
I wanted to check out the theme, but it just redirects to your GitHub profile.

**Comment by JamesMessinger** [comment]
The [redirect is intentional](https://github.com/APIDevTools/apidevtools.github.io/blob/master/index.html#L23), since we don't have a homepage yet.  But you can find the Jekyll theme here:

https://github.com/APIDevTools/gh-pages-theme
